[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "mongoose", "bcryptjs", "jsonwebtoken"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18.19.0"

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 3000
  port = 8888
  publish = "build"
