[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "mongoose"]
  included_files = ["backend/models/**"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_NETLIFY = "true"
  NODE_ENV = "production"

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 3000
  port = 8888
  publish = "build"
