[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = ["express", "mongoose", "serverless-http"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"
