[build]
  functions = "netlify/functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"

[functions]
  external_node_modules = ["express", "mongoose"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
